export const GET_PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const GET_PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const GET_PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PATCH_PRODUCT = "PATCH_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
