
export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_LOADING="GET_USER_LOADING";
export const GET_USER_FAILURE="GET_USER_FAILURE";

export const GET_SINGLE_USER_SUCCESS="GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_REQUEST="GET_SINGLE_USER_REQUEST";
export const GET_SINGLE_USER_FAILURE="GET_SINGLE_USER_FAILURE";
