export const PRODUCT_REQUEST="PRODUCT_REQUEST";
export const PRODUCT_FAILURE="PRODUCT_FAILURE";
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_SUCCESS="SINGLE_PRODUCT_SUCCESS";

export const AUTH_SUCCESS="AUTH_SUCCESS"
export const AUTH_FAILURE="AUTH_FAILURE"